[package]
name = "json_serial"
version = "0.1.0"
edition = "2024"
authors = ["bjfssd757"]
description = "This library will help you work with Json format"
license = "Apache-2.0"
repository = "https://github.com/bjfssd757/json_serial"

[dependencies]
